version: '3'
services:
  ctt_db:
    image: 'postgres:11-alpine'
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
